services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/front/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://api:4000
      - RPC_URL=${RPC_URL:-http://forlong.io:8545}
      - CHAIN_ID=${CHAIN_ID:-31337}
      - DEFAULT_ACCOUNTS=${DEFAULT_ACCOUNTS:-}
    depends_on:
      - api
    networks:
      - blockchain-explorer

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "${API_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - API_PORT=4000
      - RPC_URL=${RPC_URL:-http://forlong.io:8545}
      - CHAIN_ID=${CHAIN_ID:-31337}
    networks:
      - blockchain-explorer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  blockchain-explorer:
    driver: bridge
# 개발용 오버라이드를 위한 추가 compose 파일
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
